version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/ap-postgres-lab06:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=projektap
      - POSTGRES_USER=projektap
      - POSTGRES_DB=projektap